Count,Message,Traceback,Nodes
1,Cannot choose from an empty sequence,"  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/gsd/benchmark/wiki/locustfiles/staticRead.py"", line 20, in readPage
    actions.loadPage(self, random.choice(pages)[""path""])
  File ""/usr/lib/python3.8/random.py"", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
","c, l, o, u, d, 5, 0, _, 5, 1, 5, 0, e, e, 1, b, 4, 7, b, a, 4, 4, 5, a, 9, f, 7, 3, 1, 2, e, 6, c, 9, 9, e, 8, 8, 3, f"
2,Cannot choose from an empty sequence,"  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/gsd/benchmark/wiki/locustfiles/staticRead.py"", line 20, in readPage
    actions.loadPage(self, random.choice(pages)[""path""])
  File ""/usr/lib/python3.8/random.py"", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
","c, l, o, u, d, 6, 9, _, 8, 4, 2, c, b, 9, 9, 0, 3, d, b, 6, 4, f, 8, 2, a, c, d, 2, 9, d, 9, b, 4, a, c, b, 3, d, 9, 8"
