Count,Message,Traceback,Nodes
88,Cannot choose from an empty sequence,"  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/usr/local/lib/python3.8/dist-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/gsd/benchmark/wiki/locustfiles/simulateUser.py"", line 37, in readPage
    actions.loadPage(self, random.choice(pages)[""path""])
  File ""/usr/lib/python3.8/random.py"", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
","c, l, o, u, d, 5, 0, _, b, 5, e, f, b, 9, c, 2, 4, 7, 3, 3, 4, 0, c, 8, b, 7, b, 3, 8, 9, 0, e, c, 6, 7, e, f, d, f, 1, ,,  , c, l, o, u, d, 5, 0, _, 6, a, 8, 5, b, 6, 5, c, f, 3, 4, 8, 4, d, 1, c, a, c, c, 1, 3, d, 7, 6, e, 5, 3, 7, a, 3, 4, 5"
84,Cannot choose from an empty sequence,"  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 290, in run
    self.execute_next_task()
  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 315, in execute_next_task
    self.execute_task(self._task_queue.pop(0))
  File ""/home/gsd/.local/lib/python3.8/site-packages/locust/user/task.py"", line 428, in execute_task
    task(self.user)
  File ""/home/gsd/benchmark/wiki/locustfiles/simulateUser.py"", line 37, in readPage
    actions.loadPage(self, random.choice(pages)[""path""])
  File ""/usr/lib/python3.8/random.py"", line 290, in choice
    raise IndexError('Cannot choose from an empty sequence') from None
","c, l, o, u, d, 6, 9, _, a, 2, f, b, 4, e, f, 1, f, 9, d, 4, 4, 7, 4, b, a, c, 7, f, 1, b, 4, c, 8, 3, 7, e, 7, a, 9, 1, ,,  , c, l, o, u, d, 6, 9, _, 5, 7, 2, f, 2, e, 6, 0, 2, d, 6, e, 4, 9, 2, 0, 8, d, 3, 8, 7, 3, a, 4, b, 7, d, 2, 1, d, 3, 9"
