[2021-05-31 11:09:37,188] cloud69/WARNING/locust.main: System open file limit '1024' is below minimum setting '10000'. It's not high enough for load testing, and the OS didn't allow locust to increase it by itself. See https://github.com/locustio/locust/wiki/Installation#increasing-maximum-number-of-open-files-limit for more info.
[2021-05-31 11:09:37,189] cloud69/INFO/locust.main: Starting Locust 1.5.3
[2021-05-31 11:09:37,535] cloud69/INFO/locust.runners: Spawning 6 users at the rate 0.125 users/s (0 users already running)...
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/users.py", line 166, in run_user
    user.run()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/users.py", line 132, in run
    self.on_start()
  File "/home/gsd/benchmark/peertube/locustfiles/upload.py", line 54, in on_start
    self.token = resptoken.json()['access_token']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-31T11:10:09Z <Greenlet at 0x7fd134652ae0: run_user(<upload.QuickstartUser object at 0x7fd137dd56a0>)> failed with JSONDecodeError

[2021-05-31 11:10:17,541] cloud69/INFO/locust.runners: All users spawned: QuickstartUser: 6 (5 total running)
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/users.py", line 166, in run_user
    user.run()
  File "/home/gsd/.local/lib/python3.8/site-packages/locust/user/users.py", line 132, in run
    self.on_start()
  File "/home/gsd/benchmark/peertube/locustfiles/upload.py", line 54, in on_start
    self.token = resptoken.json()['access_token']
  File "/usr/lib/python3/dist-packages/requests/models.py", line 897, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3/dist-packages/simplejson/__init__.py", line 518, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/usr/lib/python3/dist-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2021-05-31T11:10:17Z <Greenlet at 0x7fd134652bf0: run_user(<upload.QuickstartUser object at 0x7fd137b3fc40>)> failed with JSONDecodeError

[2021-05-31 11:24:37,539] cloud69/INFO/locust.runners: Stopping 4 users
[2021-05-31 11:24:37,539] cloud69/INFO/locust.runners: 4 Users have been stopped, 0 still running
[2021-05-31 11:24:37,540] cloud69/INFO/locust.runners: Got quit message from master, shutting down...
[2021-05-31 11:24:37,540] cloud69/INFO/locust.main: Running teardowns...
[2021-05-31 11:24:37,541] cloud69/INFO/locust.main: Shutting down (exit code 0), bye.
[2021-05-31 11:24:37,541] cloud69/INFO/locust.main: Cleaning up runner...
